### ISSUE TITLE
idea 2021.1.1 不兼容

### ISSUE THREAD

**Issue by 592146505** [luchuanbaker/MyPojoToJson#2]
迄今为止用过最好的pojoToJson插件 但是最新版本的idea并不能兼容，插件市场也不再能搜到，还是希望作者能继续维护，感激不尽！

**Comment by luchuanbaker** [comment]
肯定可以兼容，但是需要修改配置，等下周我改个配置就好了

**Comment by luchuanbaker** [comment]
> 迄今为止用过最好的pojoToJson插件 但是最新版本的idea并不能兼容，插件市场也不再能搜到，还是希望作者能继续维护，感激不尽！

已经更新新版本了，在2021.3版本前都可以兼容，后面的兼容需要改代码了(气泡提示的api需要兼容新版)。

后面提需求可以去插件的反馈界面提：https://plugins.jetbrains.com/plugin/15766-my-pojo-to-json/reviews
