### ISSUE TITLE
idea 2021.3无法使用

### ISSUE THREAD

**Issue by 592146505** [luchuanbaker/MyPojoToJson#3]
这个插件是我目前所用到最好的javabean 转 json的插件了，单现在idea2021.3无法使用该插件，跪求作者更新支持一波。

**Comment by luchuanbaker** [comment]
> 这个插件是我目前所用到最好的javabean 转 json的插件了，单现在idea2021.3无法使用该插件，跪求作者更新支持一波。

惭愧，我还在使用2018、2019版本，我没有购买2021版本的序列号，暂时没有此环境，等后续有需求再说了，抱歉了。

**Comment by luchuanbaker** [comment]
> 这个插件是我目前所用到最好的javabean 转 json的插件了，单现在idea2021.3无法使用该插件，跪求作者更新支持一波。

已经升级到1.0.4版本了，等审核通过以后就可以看到了
